_commit: v1.1.0
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: network-policies.yaml
helm: false
ingClass: nginx-crt-house
ingExtraAnnotations: |-
  nginx.ingress.kubernetes.io/backend-protocol: HTTP
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
ingHost: argo.crt.house
ingName: argocd
ingPathType: Prefix
ingSvcName: argocd-server
ingSvcPortNum: 8080
ingWebSockets: false
labels: 'app: argocd'
name: argocd
namespace: argocd
resources:
- crds.yaml
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- rbac.yaml
- secrets.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
svcName: argocd-server
svcPortNum: 8080
upstreamURL: https://argoproj.github.io/cd/
url: https://github.com/charlesthomas/homelab-argocd
