_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: network-policies.yaml
backups: false
helm: false
homepageDescription: Cluster Updater
homepageGroup: Kubernetes
homepageIcon: argocd
homepageName: ArgoCD
ingress: false
labels: 'app: argocd'
name: argocd
namespace: argocd
pvc: false
reloader: true
resources:
- crds.yaml
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- rbac.yaml
- secrets.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
upstreamURL: https://argoproj.github.io/cd/
url: https://github.com/charlesthomas/homelab-argocd
