---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

commonLabels:
  app: argocd

resources:
- configmaps.yaml
- external-secrets.yaml
- ingresses.yaml
- namespaces.yaml
- statefulsets.yaml
- crds.yaml
- network-policies.yaml
- rbac.yaml
- secrets.yaml
- service-accounts.yaml
- services.yaml
